### ISSUE TITLE
Preview engine used ?

### ISSUE THREAD

**Issue by aRandomKiwi** [saveryanov/worldmap-generator#1]
Hi @saveryanov,

First of all, great work, this library looks promising for HTML5 gamedevs, i have a little question however, what engine did you use for previewing the generated map ?

Thanks
-

**Comment by saveryanov** [comment]
Hi, @Kiwy404. Sorry it took me so long to answer.

Images from README.md are just png pictures rendered by Jimp module (https://www.npmjs.com/package/jimp). It's not a fast solution, but this library was written with no external or native dependencies and it's good for examples like that.

You can find examples here: https://github.com/saveryanov/worldmap-generator/tree/master/examples
